# Generated by Django 5.1.3 on 2025-09-09 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='opportunityhost',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='opportunities.opportunityhost'),
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.role'),
        ),
        migrations.AddField(
            model_name='application',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.role'),
        ),
        migrations.AddField(
            model_name='roleskill',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_skills', to='opportunities.role'),
        ),
        migrations.AddField(
            model_name='roleskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skill'),
        ),
        migrations.AddIndex(
            model_name='opportunityhost',
            index=models.Index(fields=['zip_code'], name='opportuniti_zip_cod_e45be6_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityhost',
            index=models.Index(fields=['is_verified'], name='opportuniti_is_veri_2c8557_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status'], name='opportuniti_status_fb4df4_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['location_zip'], name='opportuniti_locatio_d03fed_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['start_date', 'end_date'], name='opportuniti_start_d_815147_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['featured'], name='opportuniti_feature_cec9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipant',
            index=models.Index(fields=['opportunity', 'status'], name='opportuniti_opportu_3acdf9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectparticipant',
            index=models.Index(fields=['volunteer'], name='opportuniti_volunte_b90278_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipant',
            unique_together={('opportunity', 'volunteer')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['volunteer'], name='opportuniti_volunte_149df9_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['opportunity'], name='opportuniti_opportu_26a9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='opportuniti_status_a74b0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('volunteer', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='roleskill',
            unique_together={('role', 'skill', 'skill_type')},
        ),
    ]
