# Generated by Django 5.1.3 on 2025-09-25 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='external_source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_crawled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CrawlerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('platform', 'Platform (VolunteerMatch, Idealist, etc.)'), ('nonprofit', 'Individual Nonprofit Website'), ('aggregator', 'Aggregator/Directory'), ('rss', 'RSS Feed'), ('api', 'API')], max_length=20)),
                ('base_url', models.URLField(max_length=500)),
                ('crawler_class', models.CharField(help_text='Python class name for the crawler', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('crawl_frequency_hours', models.PositiveIntegerField(default=24, help_text='Hours between crawls')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Crawler-specific configuration')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom headers for requests')),
                ('rate_limit_delay_seconds', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('max_pages_per_crawl', models.PositiveIntegerField(default=100)),
                ('last_crawl_time', models.DateTimeField(blank=True, null=True)),
                ('last_crawl_status', models.CharField(blank=True, max_length=50)),
                ('last_crawl_error', models.TextField(blank=True)),
                ('total_opportunities_found', models.PositiveIntegerField(default=0)),
                ('total_opportunities_imported', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'last_crawl_time'], name='opportuniti_is_acti_62a75d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrawledOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('external_id', models.CharField(blank=True, help_text='ID from the source system', max_length=200)),
                ('raw_data', models.JSONField(help_text='Complete raw data from crawler')),
                ('title', models.CharField(max_length=300)),
                ('organization_name', models.CharField(max_length=300)),
                ('organization_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('location_text', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('is_remote', models.BooleanField(default=False)),
                ('start_date_text', models.CharField(blank=True, max_length=200)),
                ('end_date_text', models.CharField(blank=True, max_length=200)),
                ('parsed_start_date', models.DateField(blank=True, null=True)),
                ('parsed_end_date', models.DateField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('time_commitment_text', models.CharField(blank=True, max_length=300)),
                ('skills_text', models.TextField(blank=True)),
                ('cause_areas_text', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('imported', 'Imported')], default='pending', max_length=20)),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, help_text='0-1 score based on data completeness', max_digits=3)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.crawledopportunity')),
                ('imported_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.opportunity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawled_opportunities', to='opportunities.crawlersource')),
            ],
            options={
                'ordering': ['-crawled_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='opportuniti_source__820d31_idx'), models.Index(fields=['status', 'quality_score'], name='opportuniti_status_f929b8_idx'), models.Index(fields=['organization_name'], name='opportuniti_organiz_e0d68b_idx')],
            },
        ),
    ]
