version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: mishmob-db
    environment:
      POSTGRES_DB: mishmob_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5433:5432"  # Map to 5433 to avoid conflicts with local PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mishmob-backend
    volumes:
      # Mount the entire backend directory for hot-reloading
      - ./backend:/app
      # Prevent overwriting of installed packages
      - /app/venv
    ports:
      - "9000:9000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-this-in-production
      - DATABASE_NAME=mishmob_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080,http://frontend:8080
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mishmob-frontend
    volumes:
      # Mount the frontend directory for hot-reloading
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/package.json:/app/package.json
      # Prevent overwriting of node_modules
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:9000/api
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  default:
    name: mishmob-network