# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do
  desc "Build a release AAB"
  lane :build do
    gradle(
      task: "clean bundleRelease",
      project_dir: "android/",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"],
      }
    )
  end

  desc "Deploy to Google Play Internal Testing"
  lane :internal do
    build
    upload_to_play_store(
      track: 'internal',
      aab: 'android/app/build/outputs/bundle/release/app-release.aab',
      json_key: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
      package_name: "com.mishmobmobile",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to Google Play Alpha Testing"
  lane :alpha do
    build
    upload_to_play_store(
      track: 'alpha',
      aab: 'android/app/build/outputs/bundle/release/app-release.aab',
      json_key: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
      package_name: "com.mishmobmobile",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to Google Play Beta Testing"
  lane :beta do
    build
    upload_to_play_store(
      track: 'beta',
      aab: 'android/app/build/outputs/bundle/release/app-release.aab',
      json_key: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
      package_name: "com.mishmobmobile",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to Google Play Production"
  lane :production do
    build
    upload_to_play_store(
      track: 'production',
      aab: 'android/app/build/outputs/bundle/release/app-release.aab',
      json_key: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
      package_name: "com.mishmobmobile",
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false
    )
  end

  desc "Promote from internal to alpha"
  lane :promote_to_alpha do
    upload_to_play_store(
      track: 'internal',
      track_promote_to: 'alpha',
      json_key: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
      package_name: "com.mishmobmobile",
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Promote from alpha to beta"
  lane :promote_to_beta do
    upload_to_play_store(
      track: 'alpha',
      track_promote_to: 'beta',
      json_key: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
      package_name: "com.mishmobmobile",
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Promote from beta to production"
  lane :promote_to_production do
    upload_to_play_store(
      track: 'beta',
      track_promote_to: 'production',
      json_key: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
      package_name: "com.mishmobmobile",
      skip_upload_aab: true,
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false
    )
  end
end