apiVersion: apps/v1
kind: Deployment
metadata:
  name: mishmob-backend
  namespace: mishmob
  labels:
    app: mishmob-backend
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mishmob-backend
  template:
    metadata:
      labels:
        app: mishmob-backend
        component: backend
    spec:
      containers:
      - name: backend
        image: mishmob/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: http
        env:
        - name: DATABASE_HOST
          value: postgres-service
        - name: DATABASE_PORT
          value: "5432"
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: backend-config
        livenessProbe:
          httpGet:
            path: /api/health
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mishmob-backend-service
  namespace: mishmob
spec:
  selector:
    app: mishmob-backend
  ports:
  - port: 9000
    targetPort: 9000
    name: http
  type: ClusterIP