apiVersion: apps/v1
kind: Deployment
metadata:
  name: mishmob-frontend
  namespace: mishmob
  labels:
    app: mishmob-frontend
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mishmob-frontend
  template:
    metadata:
      labels:
        app: mishmob-frontend
        component: frontend
    spec:
      containers:
      - name: frontend
        image: mishmob/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: VITE_API_URL
          value: "http://mishmob-backend-service:9000/api"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: mishmob-frontend-service
  namespace: mishmob
spec:
  selector:
    app: mishmob-frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP