apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mishmob

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - postgres-deployment.yaml
  - ingress.yaml

configMapGenerator:
  - name: backend-config
    literals:
      - DEBUG=False
      - ALLOWED_HOSTS=mishmob.com,api.mishmob.com
      - CORS_ALLOWED_ORIGINS=https://mishmob.com

secretGenerator:
  - name: backend-secrets
    literals:
      - SECRET_KEY=change-this-in-production
      - DATABASE_NAME=mishmob_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=change-this-password

commonLabels:
  app.kubernetes.io/name: mishmob
  app.kubernetes.io/part-of: mishmob-platform