apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend
  labels:
    app: mishmob
    component: web-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mishmob
      component: web-backend
  template:
    metadata:
      labels:
        app: mishmob
        component: web-backend
    spec:
      containers:
      - name: web-backend
        image: mishmob/backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: secret-key
        - name: DATABASE_NAME
          value: "mishmob_db"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: MEILISEARCH_HOST
          value: "http://meilisearch:7700"
        - name: MEILISEARCH_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: meilisearch-secrets
              key: master-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: web-backend
  labels:
    app: mishmob
    component: web-backend
spec:
  selector:
    app: mishmob
    component: web-backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP