apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mishmob

resources:
  - namespace.yaml
  - storage-class.yaml
  - secrets.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - meilisearch-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app: mishmob
  managed-by: kustomize