# Note: This file contains example secrets. In production, use:
# - Kubernetes Secrets Manager
# - Sealed Secrets
# - External Secrets Operator
# - Vault
# DO NOT commit real secrets to version control!
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  secret-key: "CHANGE-ME-IN-PRODUCTION-USE-STRONG-SECRET"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  username: "postgres"
  password: "CHANGE-ME-IN-PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: meilisearch-secrets
type: Opaque
stringData:
  master-key: "CHANGE-ME-IN-PRODUCTION-AT-LEAST-32-CHARS"