# Generated by Django 5.1.3 on 2025-09-27 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_userprofile_is_verified_userprofile_verified_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_user_ty_4573bb_idx',
            old_name='auth_user_user_ty_90c0e9_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_zip_cod_6db8f8_idx',
            old_name='auth_user_zip_cod_a61642_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.user'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.user'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_skills', to='users.user'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
